### ISSUE TITLE
Feature Request: Support for raster and vector sources

### ISSUE THREAD

**Issue by m7mdra** [m0nac0/flutter-mapbox-gl#55]
https://github.com/flutter-mapbox-gl/maps/pull/797

**Comment by m0nac0** [comment]
Definitely something I'd like to see here as well!
There is a number of commits that could be cherry-picked since 3c0ae333faf7bf8340d2b6007f5274dc2fa34a05 from upstream. 
But I think it makes sense to cherry-pick/port them in order, and the next one would be https://github.com/flutter-mapbox-gl/maps/pull/723.
That is quite a large one and I haven't had the time to port it.

**Comment by m7mdra** [comment]
@m0nac0 
thanks for following up...

What do you think would be the best way to do this? would it be easier to clone [flutter mapbox](https://github.com/flutter-mapbox-gl/) and start all over again or simply cherry pick through them?

**Comment by m0nac0** [comment]
I think cherry-picking would be the way to go. I've already done this with a number of commits from upstream, but I haven't had time to continue with https://github.com/flutter-mapbox-gl/maps/pull/723, yet.

**Comment by dschmucki** [comment]
Sorry to ask on this already closed issue, but I would be very interested int the features implemented in https://github.com/flutter-mapbox-gl/maps/pull/723 as well. @m0nac0 is there a chance you will have time in the foreseeable future? Or is there a way to support you? I'm not that experienced with the flutter-mapbox-gl sources so it's difficult to assess what needs to be done while cherry-picking/porting the changes.

**Comment by m0nac0** [comment]
@dschmucki Thank you for your interest in this package! I've started working on https://github.com/flutter-mapbox-gl/maps/pull/723, but I can't give any promises regarding when it'll be ready. So far I've cherry-picked 3 other commits from upstream that were a prerequisite. 

One thing that would certainly be helpful is testing the latest changes from master by running the example app on iOS, Android and web (roughly in that order). I do make sure everything compiles, but it's difficult to write useful tests for this plugin and I don't really have time to test all features manually.

**Comment by m0nac0** [comment]
Well, that was faster than expected 😄 
Everyone interested in the (geojson) layers feature from upstream is very much invited to test PR https://github.com/m0nac0/flutter-maplibre-gl/pull/70, e.g. by changing `ref: main` to `ref: m0-cp-723-geojson-layers` in your pubspec.yaml. 

~~I'd be happy to get some feedback on that PR!~~
Edit: I've merged #70, but any feedback from testing that or future changes is very welcome!

**Comment by dschmucki** [comment]
@m0nac0 Thank you for porting the layers feature! I did a quick check and found some issues on Android, iOS and the web example app. Would you prefer to have them reported as new issues?

Android (layer example):
- There is still a todo in the example AndroidManifest.xml (just set exported to true and the example runs fine)
- The symbols are not showing
![image](https://user-images.githubusercontent.com/1675109/168618996-318ba0de-c10e-4da7-895f-267f5e53c0cf.png)

iOS (layer example):
- Crash on opening the page, map not showing, rendering distorted
![image](https://user-images.githubusercontent.com/1675109/168618823-3b5318fb-107e-42a2-a761-18374b936edf.png)

Web (layer example):
- Polygons not filled
![image](https://user-images.githubusercontent.com/1675109/168618734-47e4a840-2003-4d9e-acd9-2f7963d9f9b9.png)

**Comment by m0nac0** [comment]
@dschmucki Thank you for testing! Yeah, feel free to open new issues for these. Ideally, could you add some more details (OS version, browser) with which you see these issues?

- At least for web, polygons are filled for me on Firefox and Chrome, though Chrome does have an issue with loading the icons.
- I've also just tested again on iOS, it works fine for me in the simulator on iOS 13 and iOS 14. 
Edit: I've been able to reproduce it on iOS 15.4

**Comment by m0nac0** [comment]
@dschmucki The bug on iOS only happens if the layers page is the first one I open, if I first open any other page (e.g. map UI) and the layers page after that, it works (symbols aren't showing, but it doesn't crash). Can you confirm this?

(And the symbols not showing is most likely just because they aren't included in the MapLibre style, but are by default in the Mapbox style)

Edit: I've been able to reproduce the iOS bug with at least one other page, but not all of them. Could be related to the CocoaPods version if its the same issue as this https://github.com/flutter-mapbox-gl/maps/issues/1004

**Comment by dschmucki** [comment]
@m0nac0 I tested again and can confirm that it seems to be a problem with iOS 15.x in the simulator. I was able to run the example app on a real device with iOS 15.5 just fine (order of opening the page had no effect). Changing the CocoaPods version (I tried 1.10.2, 1.11.0, 1.11.3) also didn't resolve the problem.

My Chrome version is 101.0.4951.64 and Firefox 100.0.2 on macOS Monterey 12.3.1, M1, both not showing the polygon fill.

**Comment by m0nac0** [comment]
- Re iOS:
> it seems to be a problem with iOS 15.x in the simulator. I was able to run the example app on a real device with iOS 15.5 just fine (order of opening the page had no effect).

That's good to hear. I haven't been able to test on a real device, but that means this is issue a much lower priority and not a blocker.

- Re web (filled polygons): I assume that's due to Safari or the M1 then. If you have time, could you test the flutter-mapbox-gl example app? (I don't have access to a Mac to test it)

**Comment by m0nac0** [comment]
@dschmucki And regarding

> The symbols are not showing

This should be fixed in #95. The issue was simply that the examples used iconImages that are included in Mapbox styles, but not in the simple Maplibre demo style.

**Comment by dschmucki** [comment]
@m0nac0 
* Polygon fill works on flutter-mapbox-gl (tested with Chrome, Firefox, Safari), so it seems to be an issue with Maplibre on M1? 
* Symbols are now showing, but seem twice as big on web as on mobile.
* (Tested with the latest commits (Maplibre iOS dependency update), iOS still not working in the simulator.)
